[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "I",    # isort
  "B",    # flake8-bugbear
  "UP",   # pyupgrade
  "C4",   # flake8-comprehensions
  "TID",  # flake8-tidy-imports
  "SIM",  # flake8-simplify
]
ignore = [
  "E501",  # line too long (handled by Black)
]
unfixable = ["B"]  # do not auto-fix bug-prone code

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # allow unused imports in package inits